// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Preject2netAsp.Models;

namespace Preject2netAsp.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20190612204753_migrationsAllDataBases")]
    partial class migrationsAllDataBases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Preject2netAsp.Models.Friends", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("EmailFriends");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("friend");
                });

            modelBuilder.Entity("Preject2netAsp.Models.PlayListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AudioStream");

                    b.Property<DateTime>("DateToAdd");

                    b.Property<string>("Email");

                    b.Property<string>("titleAudio");

                    b.HasKey("Id");

                    b.ToTable("playList");
                });

            modelBuilder.Entity("Preject2netAsp.Models.TracksTops", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album_Image");

                    b.Property<string>("Album_name");

                    b.Property<string>("Albums_id");

                    b.Property<string>("Artist_id");

                    b.Property<string>("Artist_idstr");

                    b.Property<string>("Artist_name");

                    b.Property<string>("Audio");

                    b.Property<string>("Audiodownload");

                    b.Property<string>("Duration");

                    b.Property<string>("License_ccurl");

                    b.Property<string>("Name");

                    b.Property<string>("Position");

                    b.Property<string>("Releasedate");

                    b.HasKey("Id");

                    b.ToTable("toptraks");
                });

            modelBuilder.Entity("Preject2netAsp.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Creation");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Role");

                    b.HasKey("Id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
